package ru.dcsoyuz.ad3s.config;

/**
 * Created by yuri.filatov on 15.07.2016.
 */
public enum ConfProp {

    FILE_PATH_HEX_CODES,

    FILE_PATH_MSIM_HEX_CODES,

    FILE_PATH_BASE_HEX,

    FILE_PATH_RECORD_TXT,

    FILE_PATH_WAVE_DATA,
    FILE_PATH_CURRENT_FILE,
    FILE_PATH_RDL_FILE,
    FILE_PATH_POKE_FILE,
    FILE_PATH_DEFINE_TXT_FILE,
    FILE_PATH_HTML_FILE,
    FILE_PATH_ENV_ENUMS,
    FILE_PATH_ENV_REG_FIELDS,
    FILE_PATH_ENV_REGS,
    FILE_PATH_ENV_ALL_REG_ADDR,
    FILE_PATH_ENV_INIT_ALL_REG_ADDR,

    RECORD_FOLDER,

    COM_PORT,

    CURRENT_MAIN_TAB,

    VIEW_GRAPH_DOB,

    VIEW_COMBINED_RANGE;

}

